/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/ALL2.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-3.82, 0.99, 1.2]} rotation={[0, 1.41, 0]} scale={0.39}>
        <group position={[0.27, 0.5, -0.3]} rotation={[Math.PI, -0.83, 2.3]}>
          <group position={[0, 0.4, 0]} rotation={[0, 0, 0.05]}>
            <group position={[0, 0.45, 0]} rotation={[-0.02, 0.01, 0.5]}>
              <group position={[0, 0.33, 0]} rotation={[-0.01, -0.01, 0.62]} />
            </group>
            <group position={[0.01, 0.48, -0.13]} rotation={[-0.03, -0.04, -2.47]}>
              <group position={[0, 0.56, 0]} rotation={[-0.01, 0.01, 0.39]} />
            </group>
            <group position={[0.01, 0.48, 0.13]} rotation={[-3.13, -0.02, -0.67]}>
              <group position={[0, 0.56, 0]} rotation={[0.08, -0.02, -0.39]} />
            </group>
          </group>
          <group position={[-0.02, -0.13, 0]} rotation={[-1.82, 0.33, -2.66]}>
            <group position={[0, 0.5, 0]} rotation={[1.25, -0.65, 0.15]} />
          </group>
          <group position={[0.07, -0.06, -0.12]} rotation={[-0.04, 0, -0.14]}>
            <group position={[0, 0.49, 0]} rotation={[0.01, -0.07, -2.35]} />
          </group>
          <group position={[0.07, -0.06, 0.12]} rotation={[-3.07, 0.03, -3]}>
            <group position={[0, 0.49, 0]} rotation={[0.01, 0.07, 2.35]} />
          </group>
        </group>
        <group position={[11.71, 0.51, -10.79]}>
          <mesh geometry={nodes.Object_0069.geometry} material={materials.orangeLis} />
          <mesh geometry={nodes.Object_0069_1.geometry} material={materials.whiteLis} />
          <mesh geometry={nodes.Object_0069_2.geometry} material={materials.blackLis} />
          <mesh geometry={nodes.Object_0069_3.geometry} material={materials.pinkLis} />
          <mesh geometry={nodes.Object_0069_4.geometry} material={materials['glow red.050']} />
          <mesh geometry={nodes.Object_0069_5.geometry} material={materials.glowGreen} />
          <mesh geometry={nodes.Object_0069_6.geometry} material={materials.testDangoTexture} />
          <mesh geometry={nodes.Object_0069_7.geometry} material={nodes.Object_0069_7.material} />
          <mesh geometry={nodes.Object_0069_8.geometry} material={materials['1BLACK']} />
          <mesh geometry={nodes.Object_0069_9.geometry} material={materials['glow grey']} />
          <mesh geometry={nodes.Object_0069_10.geometry} material={materials['glow blue']} />
          <mesh geometry={nodes.Object_0069_11.geometry} material={materials['glow dark blue']} />
          <mesh geometry={nodes.Object_0069_12.geometry} material={materials.glass} />
          <mesh geometry={nodes.Object_0069_13.geometry} material={materials['glow pink.002']} />
          <mesh geometry={nodes.Object_0069_14.geometry} material={materials['ghost eyes.001']} />
          <mesh geometry={nodes.Object_0069_15.geometry} material={materials['Material.313']} />
          <mesh geometry={nodes.Object_0069_16.geometry} material={materials.path} />
          <mesh geometry={nodes.Object_0069_17.geometry} material={materials['japan_map.002']} />
          <mesh geometry={nodes.Object_0069_18.geometry} material={materials.riverMaterial} />
          <mesh geometry={nodes.Object_0069_19.geometry} material={materials.rockMaterial} />
          <mesh geometry={nodes.Object_0069_20.geometry} material={materials.dangoPurple} />
          <mesh geometry={nodes.Object_0069_21.geometry} material={materials.dangoGreenDark} />
          <mesh geometry={nodes.Object_0069_22.geometry} material={materials.dangoBlueLight} />
          <mesh geometry={nodes.Object_0069_23.geometry} material={materials.dangloGreenLight} />
          <mesh geometry={nodes.Object_0069_24.geometry} material={materials.dangoBlueDark} />
          <mesh geometry={nodes.Object_0069_25.geometry} material={materials.dangoPink} />
          <mesh geometry={nodes.Object_0069_26.geometry} material={materials.dangoOrange} />
          <mesh geometry={nodes.Object_0069_27.geometry} material={materials.dangoLightOrange} />
          <mesh geometry={nodes.Object_0069_28.geometry} material={materials.dangoDark} />
          <mesh geometry={nodes.Object_0069_29.geometry} material={materials.chairMaterial} />
        </group>
      </group>
      <mesh geometry={nodes.BudkaBlog.geometry} material={materials.testTexture} />
      <mesh geometry={nodes.BudkaBricscad.geometry} material={nodes.BudkaBricscad.material} />
      <mesh geometry={nodes.budka3D.geometry} material={materials.testTexture} />
      <mesh geometry={nodes.BudkaVideos.geometry} material={materials.testTexture} />
      <mesh geometry={nodes.BudkaUnity.geometry} material={materials.testTexture} />
      <mesh geometry={nodes.BudkaWebdev.geometry} material={materials.testTexture} />
      <mesh geometry={nodes.BudkaLanguages.geometry} material={materials.testTexture} />
      <group position={[-5.94, -0.37, 9.78]}>
        <mesh geometry={nodes.Cube079.geometry} material={materials['Light.001']} />
        <mesh geometry={nodes.Cube079_1.geometry} material={materials['Lantern.001']} />
        <mesh geometry={nodes.Cube079_2.geometry} material={materials['grass specular2']} />
        <mesh geometry={nodes.Cube079_3.geometry} material={materials.PlantMaterial} />
      </group>
      <group position={[18.09, 0, 8.51]}>
        <mesh geometry={nodes.Cube007.geometry} material={materials['1BLACK']} />
        <mesh geometry={nodes.Cube007_1.geometry} material={materials['2RED']} />
        <mesh geometry={nodes.Cube007_2.geometry} material={materials['SeekPng.com_japanese-maple-png_955558.015']} />
        <mesh geometry={nodes.Cube007_3.geometry} material={materials['kindpng_509015.001']} />
        <mesh geometry={nodes.Cube007_4.geometry} material={materials['PngItem_1230215.002']} />
      </group>
      <group position={[-3.82, 1.11, 2.2]} rotation={[2.94, 0, 0]}>
        <mesh geometry={nodes.Object_0042.geometry} material={materials.testTexture} />
        <mesh geometry={nodes.Object_0042_1.geometry} material={materials.toriMaterial} />
        <mesh geometry={nodes.Object_0042_2.geometry} material={materials['2RED']} />
        <mesh geometry={nodes.Object_0042_3.geometry} material={materials.lampTexture} />
      </group>
      <group position={[-64.84, 6.26, -65.56]} rotation={[0, -0.57, 0]} scale={[2.54, 2.55, 2.04]}>
        <mesh geometry={nodes.Landscape038.geometry} material={materials['grass specular2']} />
        <mesh geometry={nodes.Landscape038_1.geometry} material={materials['grass specular2.004']} />
        <mesh geometry={nodes.Landscape038_2.geometry} material={materials['SeekPng.com_japanese-maple-png_955558.015']} />
        <mesh geometry={nodes.Landscape038_3.geometry} material={materials['PngItem_1230215.002']} />
        <mesh geometry={nodes.Landscape038_4.geometry} material={materials['kindpng_509015.001']} />
        <mesh geometry={nodes.Landscape038_5.geometry} material={materials.toriMaterial} />
        <mesh geometry={nodes.Landscape038_6.geometry} material={materials['Light.001']} />
        <mesh geometry={nodes.Landscape038_7.geometry} material={materials['Lantern.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/ALL2.glb')
