/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/AllDango.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-12.62, -0.24, 13.73]}>
        <group scale={1.78}>
          <mesh geometry={nodes.BigTree.geometry} material={materials.PlantMaterial} position={[0.2, -0.02, 0.31]} rotation={[Math.PI, -1.3, Math.PI]} scale={0.08} />
        </group>
      </group>
      <group position={[0, -96.1, -84.46]}>
        <group rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-1.94, 0.22, 7.9]} rotation={[Math.PI, -0.46, Math.PI]} scale={0.51}>
        <group position={[11.71, 0.51, -10.79]}>
          <mesh geometry={nodes.Object_0067.geometry} material={materials.orangeLis} />
          <mesh geometry={nodes.Object_0067_1.geometry} material={materials.whiteLis} />
          <mesh geometry={nodes.Object_0067_2.geometry} material={materials.blackLis} />
          <mesh geometry={nodes.Object_0067_3.geometry} material={materials.pinkLis} />
          <mesh geometry={nodes.Object_0067_4.geometry} material={materials.glowGreen} />
        </group>
      </group>
      <group position={[-6.2, 0.97, 8.55]} rotation={[Math.PI, -0.46, Math.PI]} scale={0.14}>
        <group position={[11.71, 0.51, -10.79]}>
          <mesh geometry={nodes.Object_0070.geometry} material={materials.orangeLis} />
          <mesh geometry={nodes.Object_0070_1.geometry} material={materials.whiteLis} />
          <mesh geometry={nodes.Object_0070_2.geometry} material={materials.blackLis} />
          <mesh geometry={nodes.Object_0070_3.geometry} material={materials.pinkLis} />
          <mesh geometry={nodes.Object_0070_4.geometry} material={materials['glow pink.002']} />
        </group>
      </group>
      <group position={[-10.57, 0.66, 7.58]} rotation={[0, 1.21, 0]} scale={0.43}>
        <group position={[11.71, 0.51, -10.79]}>
          <mesh geometry={nodes.Object_0071.geometry} material={materials.whiteLis} />
          <mesh geometry={nodes.Object_0071_1.geometry} material={materials.blackLis} />
          <mesh geometry={nodes.Object_0071_2.geometry} material={materials.pinkLis} />
          <mesh geometry={nodes.Object_0071_3.geometry} material={materials['ghost eyes.001']} />
        </group>
      </group>
      <group position={[-12.33, -0.25, 14.7]} rotation={[-Math.PI, 0.81, -Math.PI]} scale={0.75}>
        <group position={[11.71, 0.51, -10.79]}>
          <mesh geometry={nodes.Object_0072.geometry} material={materials.blackLis} />
          <mesh geometry={nodes.Object_0072_1.geometry} material={materials.pinkLis} />
          <mesh geometry={nodes.Object_0072_2.geometry} material={materials.glowGreen} />
        </group>
      </group>
      <group position={[-12.2, -0.25, 2.48]} rotation={[-Math.PI, 1.41, -Math.PI]} scale={0.75}>
        <group position={[11.71, 0.51, -10.79]}>
          <mesh geometry={nodes.Object_0073.geometry} material={materials.whiteLis} />
          <mesh geometry={nodes.Object_0073_1.geometry} material={materials.blackLis} />
          <mesh geometry={nodes.Object_0073_2.geometry} material={materials.pinkLis} />
          <mesh geometry={nodes.Object_0073_3.geometry} material={materials['Material.313']} />
        </group>
      </group>
      <group position={[-3.82, 0.99, 1.2]} rotation={[0, 1.41, 0]} scale={0.39}>
        <group position={[11.71, 0.51, -10.79]}>
          <mesh geometry={nodes.Object_0069.geometry} material={materials.orangeLis} />
          <mesh geometry={nodes.Object_0069_1.geometry} material={materials.whiteLis} />
          <mesh geometry={nodes.Object_0069_2.geometry} material={materials.blackLis} />
          <mesh geometry={nodes.Object_0069_3.geometry} material={materials.pinkLis} />
          <mesh geometry={nodes.Object_0069_4.geometry} material={materials['glow red.050']} />
        </group>
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials.path} position={[-0.12, -0.23, 4.95]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.path} position={[-0.12, -0.23, 4.95]} />
      <mesh geometry={nodes.A_TORI002.geometry} material={materials.toriMaterial} position={[9.64, 2.25, 4.97]} />
      <mesh geometry={nodes.A_TORI005.geometry} material={materials.toriMaterial} position={[16.34, 2.25, 4.97]} />
      <group position={[-24.3, -0.34, 4.88]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials['japan_map.002']} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials['rubble.001']} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials.path} />
      </group>
      <group position={[18.09, 0, 8.51]}>
        <mesh geometry={nodes.Cube007.geometry} material={materials['1BLACK']} />
        <mesh geometry={nodes.Cube007_1.geometry} material={materials['2RED']} />
      </group>
      <mesh geometry={nodes.grassMaterial.geometry} material={materials['grass specular2']} position={[-61.95, -31.99, -35.35]} rotation={[0, 0.61, 0]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.testTexture} position={[-0.12, -0.5, 4.95]} />
      <mesh geometry={nodes.water.geometry} material={materials.riverMaterial} position={[-0.12, 9.59, -10.4]} />
      <group position={[-5.94, -0.37, 9.78]}>
        <mesh geometry={nodes.Cube079.geometry} material={materials['Light.001']} />
        <mesh geometry={nodes.Cube079_1.geometry} material={materials['Lantern.001']} />
      </group>
      <mesh geometry={nodes.Cube012.geometry} material={materials.path} position={[-8.13, -0.23, 5.98]} />
      <mesh geometry={nodes.trees3_used.geometry} material={materials['SeekPng.com_japanese-maple-png_955558.015']} position={[-10.38, 5.1, -23.25]} />
      <group position={[-21.42, -0.49, 7.82]}>
        <mesh geometry={nodes.Cube015.geometry} material={materials['japan_map.013']} />
        <mesh geometry={nodes.Cube015_1.geometry} material={materials['japan_map.002']} />
      </group>
      <mesh geometry={nodes.trees1_used.geometry} material={materials['kindpng_509015.001']} position={[-4.38, -0.47, 11.24]} />
      <mesh geometry={nodes.landToDelete1.geometry} material={materials['grass specular2']} position={[76.99, -21.15, 102.62]} rotation={[-0.03, 1.23, -0.3]} />
      <mesh geometry={nodes.trees2_used.geometry} material={materials['PngItem_1230215.002']} position={[-14.23, -0.75, 9.85]} rotation={[1.56, 0, -0.66]} />
      <mesh geometry={nodes.landToDelete7.geometry} material={materials.toriMaterial} position={[140.79, 2.25, 4.97]} />
      <mesh geometry={nodes.Chair.geometry} material={materials.chairMaterial} position={[-5.63, -0.57, 11.46]} rotation={[0.01, 0, 0]} />
      <mesh geometry={nodes.Chair2.geometry} material={materials.chairMaterial} position={[-5.63, -0.62, 14.88]} rotation={[0.01, 0, 0]} />
      <mesh geometry={nodes.wachlarz5.geometry} material={materials.testTexture} position={[-1.98, 1.11, 1.49]} rotation={[2.94, 0, 0]} />
      <mesh geometry={nodes.wachlarz4.geometry} material={materials.testTexture} position={[-3.48, 1.11, 1.49]} rotation={[2.94, 0, 0]} />
      <mesh geometry={nodes.wachlarz1.geometry} material={materials.testTexture} position={[-3.82, 1.11, 2.2]} rotation={[2.94, 0, 0]} />
      <mesh geometry={nodes.wachlarz2.geometry} material={materials.testTexture} position={[-2.74, 1.11, 2.2]} rotation={[2.94, 0, 0]} />
      <mesh geometry={nodes.wachlarz3.geometry} material={materials.testTexture} position={[-1.67, 1.11, 2.2]} rotation={[2.94, 0, 0]} />
      <mesh geometry={nodes.dangoStick.geometry} material={materials.testTexture} position={[-1.28, 0.72, 7.38]} rotation={[0, 0, -0.13]} />
      <mesh geometry={nodes.dangoReact.geometry} material={materials.testDangoTexture} position={[-1.24, 0.72, 7.38]} rotation={[0, 0, 0.04]} scale={1.22} />
      <mesh geometry={nodes.dangoMongoose.geometry} material={materials.testDangoTexture} position={[-1.31, 0.72, 7.38]} rotation={[0, 0, 0.04]} scale={1.22} />
      <mesh geometry={nodes.dangoMySql.geometry} material={materials.testDangoTexture} position={[-1.47, 0.72, 7.38]} rotation={[0, 0, 0.04]} scale={1.22} />
      <mesh geometry={nodes.dangoBlender.geometry} material={materials.testDangoTexture} position={[-1.55, 0.72, 7.38]} rotation={[0, 0, 0.04]} scale={1.22} />
      <mesh geometry={nodes.dangoSpring.geometry} material={materials.testDangoTexture} position={[-1.63, 0.72, 7.38]} rotation={[0, 0, 0.04]} scale={1.22} />
      <mesh geometry={nodes.dangoGsap.geometry} material={materials.testDangoTexture} position={[-1.71, 0.72, 7.38]} rotation={[0, 0, 0.04]} scale={1.22} />
      <mesh geometry={nodes.dangoGimp.geometry} material={materials.testDangoTexture} position={[-1.79, 0.72, 7.38]} rotation={[0, 0, 0.04]} scale={1.22} />
      <mesh geometry={nodes.dangoPaypal.geometry} material={materials.testDangoTexture} position={[-1.86, 0.72, 7.38]} rotation={[0, 0, 0.04]} scale={1.22} />
      <mesh geometry={nodes.dangoDavinci.geometry} material={materials.testDangoTexture} position={[-1.94, 0.72, 7.38]} rotation={[0, 0, 0.04]} scale={1.22} />
      <group position={[-10.81, 1.02, 1.59]}>
        <mesh geometry={nodes.Cube083.geometry} material={materials.testTexture} />
        <mesh geometry={nodes.Cube083_1.geometry} material={materials['maskRed.002']} />
      </group>
      <group position={[-9.73, 0.79, 2.2]}>
        <mesh geometry={nodes.Cube084.geometry} material={materials['maskRed.002']} />
        <mesh geometry={nodes.Cube084_1.geometry} material={materials.testTexture} />
      </group>
      <mesh geometry={nodes.mask2002.geometry} material={materials.testTexture} position={[-10.2, 1.06, 1.63]} />
      <group position={[-11.33, 0.8, 2.16]}>
        <mesh geometry={nodes.Cube086.geometry} material={materials.testTexture} />
        <mesh geometry={nodes.Cube086_1.geometry} material={materials['maskRed.002']} />
      </group>
      <mesh geometry={nodes.origamiDuck.geometry} material={materials.testTexture} position={[-5.01, 1.04, 7.98]} rotation={[0, -1.03, 0]} />
      <mesh geometry={nodes.origamiBird.geometry} material={materials.testTexture} position={[-5.52, 1.02, 8.22]} rotation={[0, -1.32, 0]} />
      <mesh geometry={nodes.origamiCapybara.geometry} material={materials.testTexture} position={[-5.97, 1.04, 8.42]} rotation={[0, -0.81, 0]} />
      <mesh geometry={nodes.origamiDinosaur.geometry} material={materials.testTexture} position={[-5.66, 0.98, 8.38]} rotation={[0, -1.09, 0]} />
      <mesh geometry={nodes.origamiFox.geometry} material={materials.testTexture} position={[-5.3, 1.1, 7.9]} rotation={[0, -1.47, 0]} />
      <mesh geometry={nodes.origamiPanda.geometry} material={materials.testTexture} position={[-5.83, 0.97, 8.71]} rotation={[Math.PI, -1.4, Math.PI]} />
      <mesh geometry={nodes.languageCardJapanese.geometry} material={materials.testTexture} position={[-10.96, 0.74, 14.96]} />
      <mesh geometry={nodes.languageCardEnglish.geometry} material={materials.testTexture} position={[-10.96, 0.74, 14.64]} />
      <mesh geometry={nodes.languageCardPolish.geometry} material={materials.testTexture} position={[-10.96, 0.74, 14.33]} />
      <mesh geometry={nodes.languageCardGerman.geometry} material={materials.testTexture} position={[-10.53, 0.74, 14.98]} />
      <mesh geometry={nodes.languageCardSpanish.geometry} material={materials.testTexture} position={[-10.53, 0.74, 14.65]} />
      <mesh geometry={nodes.languageCardChinese.geometry} material={materials.testTexture} position={[-10.53, 0.74, 14.32]} />
      <group position={[-1.45, 0.86, 7.41]} rotation={[0, 0, 0.04]} scale={0.93}>
        <mesh geometry={nodes.Sphere020.geometry} material={materials.testDangoTexture} />
        <mesh geometry={nodes.Sphere020_1.geometry} material={materials.testTexture} />
      </group>
      <mesh geometry={nodes['4_wishes006'].geometry} material={materials.testTexture} position={[-7.94, 1.24, 2.06]} />
      <mesh geometry={nodes.landToDelete4.geometry} material={materials['grass specular2']} position={[-64.84, 6.26, -65.56]} rotation={[0, -0.57, 0]} scale={[2.54, 2.55, 2.04]} />
      <mesh geometry={nodes.landToDelete3.geometry} material={materials['grass specular2']} position={[116.23, -29.23, -38.83]} rotation={[0, -0.21, 0]} scale={33.44} />
      <mesh geometry={nodes.landToDelete2.geometry} material={materials['grass specular2.004']} position={[123.99, -45.54, 66.21]} scale={33.44} />
      <group position={[-5.94, -0.37, 9.78]}>
        <mesh geometry={nodes.Cube024.geometry} material={materials['Light.001']} />
        <mesh geometry={nodes.Cube024_1.geometry} material={materials['Lantern.001']} />
      </group>
      <mesh geometry={nodes.landToDelete5.geometry} material={materials['grass specular2']} position={[-61.95, -31.99, -35.35]} rotation={[0, 0.61, 0]} />
      <group position={[-10.38, 5.1, -23.25]}>
        <mesh geometry={nodes['SeekPngcom_japanese-maple-png_955558002'].geometry} material={materials['SeekPng.com_japanese-maple-png_955558.015']} />
        <mesh geometry={nodes['SeekPngcom_japanese-maple-png_955558002_1'].geometry} material={materials['PngItem_1230215.002']} />
        <mesh geometry={nodes['SeekPngcom_japanese-maple-png_955558002_2'].geometry} material={materials['kindpng_509015.001']} />
      </group>
      <mesh geometry={nodes.BudkaProjects.geometry} material={materials.testTexture} position={[-6.62, -0.15, 1.99]} scale={1.08} />
      <mesh geometry={nodes.BudkaBricscad.geometry} material={materials.testTexture} position={[-10.95, 0.15, 8.87]} rotation={[0, -1.55, 0]} scale={1.12} />
      <group position={[-7.87, 0.69, 16.71]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube012_1.geometry} material={materials['1BLACK']} />
        <mesh geometry={nodes.Cube012_2.geometry} material={materials['glow grey']} />
        <mesh geometry={nodes.Cube012_3.geometry} material={materials['glow blue']} />
        <mesh geometry={nodes.Cube012_4.geometry} material={materials['glow dark blue']} />
        <mesh geometry={nodes.Cube012_5.geometry} material={materials.glass} />
        <mesh geometry={nodes.Cube012_6.geometry} material={materials.testDangoTexture} />
      </group>
      <mesh geometry={nodes.Budka3D.geometry} material={materials.testTexture} position={[-5.59, 0.21, 8.4]} rotation={[0, 0.65, 0]} />
      <mesh geometry={nodes.BudkaVideos.geometry} material={materials.testTexture} position={[-2.74, 0.4, 1.8]} />
      <mesh geometry={nodes.BudkaUnity.geometry} material={materials.testTexture} position={[-10.53, 0.89, 1.96]} scale={1.33} />
      <mesh geometry={nodes.BudkaWebdev.geometry} material={materials.testTexture} position={[-2.23, 0.28, 7.74]} scale={1.02} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials.testTexture} position={[-2.1, 1.76, 3.15]} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials.testTexture} position={[-9.9, 1.76, 3.15]} />
      <mesh geometry={nodes.Sphere006.geometry} material={materials.testTexture} position={[-3.74, 1.76, 6.67]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.BudkaLanguages.geometry} material={materials.testTexture} position={[-11.21, -0.53, 13.68]} rotation={[-Math.PI, 1.55, -Math.PI]} />
      <mesh geometry={nodes.Sphere004.geometry} material={materials.testTexture} position={[-9.9, 1.81, 13.07]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Sphere016.geometry} material={materials.testTexture} position={[-12.93, 1.76, 6.78]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Sphere017.geometry} material={materials.testTexture} position={[-6, 1.83, 3.15]} />
      <mesh geometry={nodes.BricscadPaper1.geometry} material={materials.testTexture} position={[-11.09, 0.35, 9.24]} rotation={[0, -1.13, 0]} scale={1.12} />
      <mesh geometry={nodes.BricscadPaper2.geometry} material={materials.testTexture} position={[-10.52, 0.36, 8.71]} rotation={[-Math.PI, 1.3, -Math.PI]} scale={1.12} />
      <mesh geometry={nodes.BricscadPaper3.geometry} material={materials.testTexture} position={[-10.43, 0.37, 8.3]} rotation={[-Math.PI, 1.44, -Math.PI]} scale={1.12} />
      <mesh geometry={nodes.BricscadPaper4.geometry} material={materials.testTexture} position={[-11.11, 1, 7.77]} rotation={[0, -1.55, 0]} scale={1.12} />
      <mesh geometry={nodes.Lampy.geometry} material={materials.lampTexture} position={[-9.9, 1.81, 8.41]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials.testTexture} position={[-9.99, 1.76, 8.41]} rotation={[0, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/AllDango.glb')
