/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/lampionsflying.glb')
  const { actions } = useAnimations(animations, group)
  const color3 = new THREE.Color("rgb(205, 50, 0)");


  useEffect(() => {
    if(!materials) return;



    materials['LANTERN.004'].toneMapped = true;
    materials['LANTERN.004'].emissive = color3;
    materials['LANTERN.004'].emissiveIntensity = 1;
  }, [materials])

  useEffect(() => {
    if (!actions) return;
    actions['LampionsFly'].loop = true;
    actions['LampionsFly'].setDuration(15)
    
    actions['LampionsFly'].play();
    
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="LampionyArmature" scale={[.9,.9,.9]} position={[22.4, -36.44, 1.98]}>
          <primitive object={nodes.LampionyFront2} />
          <primitive object={nodes.LampionyFront1} />
          <primitive object={nodes.LampionyBack2} />
          <primitive object={nodes.LampionyBack1} />
          <skinnedMesh name="FlyingLanterns" geometry={nodes.FlyingLanterns.geometry} material={materials['LANTERN.004']} skeleton={nodes.FlyingLanterns.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/lampionsflying.glb')
